Assignment2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'MovieRate.views.home_page', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^add_movie$', 'MovieRate.views.add_page',name='add'),
    url(r'^movie_detail/(\d+)/$', 'MovieRate.views.movie_detail_page', name='detail'),
    url(r'^movie/(\d+)/edit/$', 'MovieRate.views.edit_page', name='edit'),
    (r'^admin/', include(admin.site.urls)),
    url(r'^movie_comming$', 'MovieRate.views.movie_comming', name='commingsoon'),
    url(r'^movie_now$', 'MovieRate.views.movie_now', name='movienow'),
    url(r'^show_all$', 'MovieRate.views.show_all', name='showall'),
    url(r'^last_movie$', 'MovieRate.views.last_movie', name='lastmovie'),
    url(r'^top_rate$', 'MovieRate.views.top_rate', name='toprate'),
    url(r'^most_comment$', 'MovieRate.views.most_comment', name='mostcomment'),
    #url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    #(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/login/$', 'MovieRate.views.login_page', name='login'),
    #url(r'^accounts/logout/$', 'MovieRate.views.logout_page', name='logout'),
    url(r'^accounts/registration/$', 'MovieRate.views.register_page', name='register'),
    url(r'^accounts/registration_complete/$', 'MovieRate.views.register_complete_page', name='register_ok'),
)

MovieRate/models.py
from django.db import models
from datetime import datetime
from django.core import serializers


class Movie(models.Model):
    name = models.TextField(default='')
    detail = models.TextField(default='')
    lead_actors = models.TextField(default='')
    director = models.TextField(default='')
    genre = models.TextField(default='')
    release_date = models.TextField(default='')
    rate = models.FloatField(default=0)
    viewer = models.IntegerField(default=0)
    poster = models.URLField(default='')
    add_date = models.DateTimeField(default=datetime.now, blank=True)
    countcom = models.IntegerField(default=0)
    clip = models.TextField(default='')


class Comment(models.Model):
    movie = models.ForeignKey(Movie, default=None)
    user = models.TextField(default='')
    comment_text = models.TextField(default='')
    date = models.DateTimeField(default=datetime.now, blank=True)
    like = models.IntegerField(default=0)


def Movie_xml():
    XMLSerializer = serializers.get_serializer("xml")
    xml_serializer = XMLSerializer()
    with open("MovieRate/file.xml", "w") as out:
        xml_serializer.serialize(Movie.objects.all(), stream=out)

MovieRate/forms.py
from django import forms
from django.forms import ModelForm
from MovieRate.models import Movie


class MovieForm(ModelForm):

    class Meta:
        model = Movie

        fields=['name','detail','release_date','rate','viewer','poster','add_date']

MovieRate/views.py
from django.shortcuts import redirect, render
from MovieRate.models import Movie, Comment, Movie_xml
from datetime import datetime
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import serializers
import time


def home_page(request):
    if (request.method == 'POST' and request.POST.get(
      'Add_send_Detail', '') == 'submit_send_data'):
        if request.POST['name_text'] != '':
            Movie.objects.create(
                             name=request.POST['name_text'],
                             detail=request.POST['detail_text'],
                             lead_actors=request.POST['actor_text'],
                             director=request.POST['director_text'],
                             genre=request.POST['genre_text'],
                             release_date=request.POST['date_text'],
                             rate=0,
                             viewer=0,
                             poster=request.POST['poster_url'],
                             clip=request.POST['clip_url'],
                             add_date=datetime.now(),
                                 )
            Movie_xml()
        return redirect('/')
    if (request.method == 'POST' and request.POST.get(
      'back_send', '') == 'Back_send'):
        return redirect('/')
    if (request.method == 'POST' and request.POST.get(
      'send_add_data', '') == 'send_Add Movie'):
        return redirect('/')
    if(request.method == 'POST' and request.POST.get(
      'delete', '') == 'delete'):
        id_data = request.POST['id_delete']
        Movie.objects.get(pk=id_data).delete()
        Movie_xml()
        return redirect('/')
    # login
    if(request.method == 'POST' and request.POST.get(
      'send_login', '') == 'send'):
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
        else:
            alarm = 'error. please try again.'
            return render(request, 'registration/login.html', {'alarm': alarm})

    # logout
    if(request.method == 'POST' and request.POST.get(
      'submit_logout_page', '') == 'go_logout'):
        auth.logout(request)

    movies = Movie.objects.all()
    Day = int(time.strftime("%Y%m%d"))
    IDcomming = []
    IDnow = []
    Datecomming = []
    Datenow = []
    if Movie.objects.count() != 0:
        for movie in movies:
            if str(movie.release_date) != "":
                date = str(movie.release_date).split("-")
                F = ""
                for j in range(len(date)):
                    F = F+str(date[j])
                dates = int(F)
            else:
                dates = Day
            if Day < dates:
                IDcomming.append(movie.id)
                Datecomming.append(dates)
                for i in range(len(Datecomming)):
                    for j in range(len(Datecomming)):
                        if Datecomming[i] <= Datecomming[j]:
                            tempd = Datecomming[j]
                            Datecomming[j] = Datecomming[i]
                            Datecomming[i] = tempd

                            temp = IDcomming[j]
                            IDcomming[j] = IDcomming[i]
                            IDcomming[i] = temp
            else:
                IDnow.append(movie.id)
                Datenow.append(dates)
                for i in range(len(Datenow)):
                    for j in range(len(Datenow)):
                        if Datenow[i] >= Datenow[j]:
                            tempd = Datenow[j]
                            Datenow[j] = Datenow[i]
                            Datenow[i] = tempd

                            temp = IDnow[j]
                            IDnow[j] = IDnow[i]
                            IDnow[i] = temp

    return render(request, 'home.html', {
        'movies': movies, 'IDcomming': IDcomming, 'IDnow': IDnow,
        'Datenow': Datenow
                  })


def edit_page(request, movie_id):
    if (request.method == 'POST' and request.POST.get(
      'send_Edit', '') == 'send_edit'):
        movie_ = Movie.objects.get(id=movie_id)
        return render(request, 'edit.html', {'movie_': movie_})
    # แก้ไข รายละเอียดหนัง
    if (request.method == 'POST' and request.POST.get(
      'Update_send_Detail', '') == 'submit_send_update'):
        movie_ = Movie.objects.get(id=movie_id)
        if request.POST['name_text'] != '':
            movie_.name = request.POST['name_text']
        if request.POST['detail_text'] != '':
            movie_.detail = request.POST['detail_text']
        if request.POST['date_text'] != '':
            movie_.release_date = request.POST['date_text']
        if request.POST['actor_text'] != '':
            movie_.lead_actors = request.POST['actor_text']
        if request.POST['director_text'] != '':
            movie_.director = request.POST['director_text']
        if request.POST['genre_text'] != '':
            movie_.genre = request.POST['genre_text']
        if request.POST['clip_url'] != '':
            movie_.clip = request.POST['clip_url']
        if request.POST['poster_url'] != '':
            movie_.poster = request.POST['poster_url']
        movie_.add_date = movie_.add_date
        movie_.save()
        Movie_xml()
        return redirect('/movie_detail/%d' % int(movie_.id))
    return redirect('/detail')


def add_page(request):
    if request.method == 'POST':
        return redirect('/add_movie')
    return render(request, 'add.html')


def movie_detail_page(request, movie_id):
    movie_ = Movie.objects.get(id=movie_id)
    comments = Comment.objects.filter(movie=movie_)
    # rating
    if (request.method == 'POST' and request.POST.get(
      'send_rate', '') == 'send_rate'):
        star = float(request.POST.get('star', 0))
        point = int(movie_.viewer)*float(movie_.rate)
        movie_.viewer = int(movie_.viewer)+1
        movie_.rate = float(format(((point+star)/movie_.viewer), '.1f'))
        movie_.save()

    # กรณีใส่คอมเมนต์
    if (request.method == 'POST' and request.POST.get(
      'send_comment', '') == 'send_Comment'):
        if request.POST['user_name'] != '' and request.POST[
          'comment_text'] != '':
            Comment.objects.create(
                                      user=request.POST['user_name'],
                                      comment_text=request.POST[
                                        'comment_text'],
                                      date=datetime.now(),
                                      like=0,
                                      movie=movie_,)
            movie_.countcom = int(movie_.countcom)+1
            movie_.save()
            return redirect('/movie_detail/%d' % int(movie_id))
    # กรณีกดไลค์
    if(request.method == 'POST' and request.POST.get(
      'send_like', '') == 'submit_like'):
        id_comment = request.POST['id_send_like']
        comment_ = Comment.objects.get(id=id_comment)
        add_like = int(comment_.like) + 1
        comment_.like = add_like
        comment_.save()
        return redirect('/movie_detail/%d' % int(movie_id))
    return render(request, 'detail.html', {
                  'movie_': movie_, 'comments': comments})


def login_page(request):
    if(request.method == 'POST' and request.POST.get(
      'submit_login_page', '') == 'go_login'):
        return redirect('/accounts/login/')
    return render(request, 'registration/login.html')


def register_page(request):
    if(request.method == 'POST' and request.POST.get(
      'submit_regis_page', '') == 'go_regis'):
        return redirect('/accounts/registration/')
    return render(request, 'registration/registration_form.html')


def register_complete_page(request):
    # register
    alarm = ''
    if(request.method == 'POST' and request.POST.get(
      'send_register', '') == 'send'):
        username = request.POST['username']
        password = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        alarm = ''
        if (request.POST['password1'] == request.POST['password2'] and
           username != '' and request.POST['password1'] != ''):
            if User.objects.filter(username=username).count() == 0:
                new_user = User.objects.create_user(username, email, password)
                new_user.is_staff = True
                new_user.save()
                return redirect('/accounts/registration_complete/')
            else:
                alarm = "already have this username."
        else:
            alarm = "error. please try again"

        return render(request,
                      'registration/registration_form.html', {'alarm': alarm})
    return render(request, 'registration/registration_complete.html')


def movie_comming(request):
    movies = Movie.objects.all()
    Day = int(time.strftime("%Y%m%d"))
    IDcomming = []
    Datecomming = []
    if Movie.objects.count() != 0:
        for movie in movies:
            if str(movie.release_date) != "":
                date = str(movie.release_date).split("-")
                F = ""
                for j in range(len(date)):
                    F = F+str(date[j])
                dates = int(F)
            else:
                dates = Day
            if Day < dates:
                IDcomming.append(movie.id)
                Datecomming.append(dates)
                for i in range(len(Datecomming)):
                    for j in range(len(Datecomming)):
                        if Datecomming[i] <= Datecomming[j]:
                            tempd = Datecomming[j]
                            Datecomming[j] = Datecomming[i]
                            Datecomming[i] = tempd

                            temp = IDcomming[j]

MovieRate/templates/add.html
<html>
    <head>
        <title>Movie Rate App</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
    <link href="/static/style/style.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="js/jquery-func.js"></script>
        <script>
            $(document).ready(function() {
                  $("#id_new_date").datepicker({ dateFormat: 'yy-mm-dd' });
            });
        </script>
    </head>
    <body>

<!-- Shell -->
<div id="shell">
        <h1>Add New Movie</h1>

<!-- Header -->
	<div id="header">
		
{% if user.is_authenticated %}
        <form method="POST" action="/">
            <p align="right">Welcome, {{ user.get_username }}.
            <input type="submit" value="logout" id="logout" >
            <input type="hidden" value="go_logout" name="submit_logout_page" >
            {% csrf_token %}
        </form></p>
{% else %}

        <form method="POST" action="/accounts/registration/" style="float:right;">
            <input type="submit" value="signup" id="registration" >
            <input type="hidden" value="go_regis" name="submit_regis_page" >
            {% csrf_token %}
        </form>
        <form method="POST" action="/accounts/login/" style="float:right;">
            Welcome, new user. Please 
            <input type="submit" value="login" id="login" >
            <input type="hidden" value="go_login" name="submit_login_page" >
            {% csrf_token %}
            or &nbsp;
        </form>
{% endif %}
		<!-- Navigation -->
		<div id="navigation">
			<ul>
			    <li><a href="/">HOME</a></li>
			    <li><a href="/movie_now">IN THEATERS</a></li>
			    <li><a href="/movie_comming">COMING SOON</a></li>
			</ul>

		</div>
		<!-- end Navigation -->
<!-- Sub-menu -->
		<div id="sub-navigation">
			<ul>
			    <li><a href="/show_all">SHOW ALL</a></li>
			    <li><a href="/last_movie">LATEST TRAILERS</a></li>
			    <li><a href="/top_rate">TOP RATED</a></li>
			    <li><a href="/most_comment">MOST COMMENTED</a></li>
			</ul>
			</div>
		<!-- end Sub-Menu -->

</div>
	<!-- end Header -->

        <form method="POST" action="/">
<table>
<tr><td>Name<h style="color:red">*</h>:   
</td><td><input name="name_text" id="id_new_name" placeholder="New Movie Name" required
    oninvalid="this.setCustomValidity('Please Enter the movie name')"
    oninput="setCustomValidity('')"/>
</td></tr>

<tr><td>
<div class="cleaner h15"></div>  
</td><td><div class="cleaner h15"></div> 
</td></tr>

<tr><td>
Release Date:    
</td><td><input name="date_text" id="id_new_date" placeholder="Add Release Date">
</td></tr>

<tr><td>
<div class="cleaner h20"></div>  
</td><td><div class="cleaner h20"></div> 
</td></tr>

<tr><td>
Lead Actors:    
</td><td><input name="actor_text" id="id_new_actor" placeholder="Add Lead Actors" />
</td></tr>

<tr><td>
<div class="cleaner h15"></div>  
</td><td><div class="cleaner h15"></div> 
</td></tr>

<tr><td>
Director:    
</td><td><input name="director_text" id="id_new_director" placeholder="Add Director" />
</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Genre:    
</td><td><input name="genre_text" id="id_new_genre" placeholder="Add Type Of Movie" />
</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Detail:    
</td><td><br><textarea name="detail_text" id="id_new_detail" placeholder="Add Details"  /></textarea>
</td></tr>

<tr><td>
<div class="cleaner h20"></div>  
</td><td><div class="cleaner h20"></div> 
</td></tr>

<tr><td>
Poster Image URL:    
</td><td><input name="poster_url" id="id_new_pic" placeholder="Add Poster URL" />
</td></tr>

<tr><td>
<div class="cleaner h15"></div>  
</td><td><div class="cleaner h15"></div> 
</td></tr>

<tr><td>
Clip URL:    
</td><td><input name="clip_url" id="id_new_clip" placeholder="Add Clip URL" />
</td></tr>



</table>
            <input type="submit" value="Add Detail"        id="submit_data"  >
            <input type="hidden" value="submit_send_data"  name="Add_send_Detail">
	    <br>
            {% csrf_token %}
        </form>
        <form method="POST" action="/">
            <input type="submit" value="Back" id="back" >
            <input type="hidden" value="Back_send" name="back_send" >
	    <br>
            {% csrf_token %}
        </form>

</div>
<!-- end Shell -->
    </body>
</html>

MovieRate/templates/detail.html
<html>
    <head>
        <title>Movie Rate App</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link href="/static/style/style.css" rel="stylesheet" media="screen">
    <link href="/static/style/star.css" rel="stylesheet" media="screen">

	<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="js/jquery-func.js"></script>

    </head>
    <body>
<!-- Shell -->
<div id="shell">
<h1>Detail of {{ movie_.name }} </h1>
<!-- Header -->
	<div id="header">
		
{% if user.is_authenticated %}
        <form method="POST" action="/">
            <p align="right">Welcome, {{ user.get_username }}.
            <input type="submit" value="logout" id="logout" >
            <input type="hidden" value="go_logout" name="submit_logout_page" >
            {% csrf_token %}
        </form></p>
{% else %}

        <form method="POST" action="/accounts/registration/" style="float:right;">
            <input type="submit" value="signup" id="registration" >
            <input type="hidden" value="go_regis" name="submit_regis_page" >
            {% csrf_token %}
        </form>
        <form method="POST" action="/accounts/login/" style="float:right;">
            Welcome, new user. Please 
            <input type="submit" value="login" id="login" >
            <input type="hidden" value="go_login" name="submit_login_page" >
            {% csrf_token %}
            or &nbsp;
        </form>
{% endif %}
		<!-- Navigation -->
		<div id="navigation">
			<ul>
			    <li><a href="/">HOME</a></li>
			    <li><a href="/movie_now">IN THEATERS</a></li>
			    <li><a href="/movie_comming">COMING SOON</a></li>
			</ul>

		</div>
		<!-- end Navigation -->
<!-- Sub-menu -->
		<div id="sub-navigation">
			<ul>
			    <li><a href="/show_all">SHOW ALL</a></li>
			    <li><a href="/last_movie">LATEST TRAILERS</a></li>
			    <li><a href="/top_rate">TOP RATED</a></li>
			    <li><a href="/most_comment">MOST COMMENTED</a></li>
			</ul>
			</div>
		<!-- end Sub-Menu -->

</div>
	<!-- end Header -->
<div class="cleaner h40"></div>
   <div class="test">     
<table id="id_list_table" align="center">
<tr><td>
Name: </td><td> {{ movie_.name }}</td></tr>
<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Release Date:  </td><td>  {{ movie_.release_date }}</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Lead Actors:  </td><td>  {{ movie_.lead_actors }}</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Director:  </td><td>  {{ movie_.director }}</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Genre:  </td><td>  {{ movie_.genre }}</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Detail:  </td><td>  {{ movie_.detail }}</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Poster Image URL:  </td><td>  <img src=" {{ movie_.poster }} " height=600 ></td></tr>


<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Add Date: </td><td>   {{ movie_.add_date }}</td></tr>

<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
Rate:  </td><td>  {{ movie_.rate }}</td></tr>

<tr><td>
<div class="cleaner h40"></div>  
</td><td><div class="cleaner h40"></div> 
</td></tr>

<tr><td>
Clip : </td><td> 
<iframe width="420" height="345"
src="{{ movie_.clip }}">
</iframe>

</td></tr>


<tr><td>
<div class="cleaner h10"></div>  
</td><td><div class="cleaner h10"></div> 
</td></tr>

<tr><td>
</td><td>   <form method="POST" action="/movie_detail/{{movie_.id}}/">
<div class="stars">
    <input class="star star-5" id="star-5" type="radio" name="star" value=5 />
    <label class="star star-5" for="star-5"></label>
    <input class="star star-4" id="star-4" type="radio" name="star" value=4 />
    <label class="star star-4" for="star-4"></label>
    <input class="star star-3" id="star-3" type="radio" name="star" value=3 />
    <label class="star star-3" for="star-3"></label>
    <input class="star star-2" id="star-2" type="radio" name="star" value=2 />
    <label class="star star-2" for="star-2"></label>
    <input class="star star-1" id="star-1" type="radio" name="star" value=1 />
    <label class="star star-1" for="star-1"></label>
</div>
            <input type="submit" value="rate"        id="id_rate"  >
            <input type="hidden" value="send_rate"  name="send_rate">
	    <br>
            {% csrf_token %}
        </form></td></tr>
</table>
  </div>     


<div class="cleaner h40"></div>
<div class="wTable">
<table id="comment_text" align="center">

        {% if movie_.countcom != 0 %}
           <h2>COMMENTS</h2>
            {% for comment in comments %}

           <tr id="comment_{{ comment.id }}_name"><td> <b>Name: </b>{{ comment.user }}</td></tr>
           <tr id="comment_{{ comment.id }}_date"><td><span class="date"> date:{{ comment.date }}<br></span></td></tr>
           <tr id="comment_{{ comment.id }}_comment"><td><span class="comment"> <b>comment:</b> {{ comment.comment_text }}<br></span></td></tr>
           <tr id="comment_{{ comment.id }}_like"><td><span class="like"><b> Like:{{ comment.like }}<br></b></span></td></tr>
       <tr><td> <form method="POST" action="/movie_detail/{{movie_.id}}/">
            <input type="submit" value="LIKE"        id="submit_like_{{ comment.id }}"  >
            <input type="hidden" value="submit_like"  name="send_like">
            <input type="hidden" value="{{ comment.id }}"  name="id_send_like">
                
            {% csrf_token %}
        </form></td></tr>
<tr><td> </td></tr>
<tr><td> </td></tr>
<tr><td><div class="cleaner h20"></div> </td></tr>
            {% endfor %}
        {% endif%}
</table>
</div>







<div class="cleaner h40"></div>
<div id="comment_form">
<h3>Comment</h3>
 <form method="POST" name="comment" action="/movie_detail/{{movie_.id}}/">
{% if user.is_authenticated %}

           <div class="form_row"> <label for="text">name<h style="color:red">*</h>: {{ user.get_username }}</label><br/> 
<input name="user_name" id="id_user_name_comment" value="{{ user.get_username }}" type="hidden"></div>

            <br/>
{% else %}

           <div class="form_row"> <label for="text">name<h style="color:red">*</h>:</label><br/> <input name="user_name" id="id_user_name_comment" placeholder="Your Name" required
    oninvalid="this.setCustomValidity('Please Enter your name')"
    oninput="setCustomValidity('')"/></div>
            <br/>
{% endif%}
          <div class="form_row">  <label for="text">Message<h style="color:red">*</h>:</label> <br/><textarea name="comment_text" id="id_comment_text" placeholder="Comment this movie" class="validate-email required input_field" required
    oninvalid="this.setCustomValidity('Please Enter some comment message')"
    oninput="setCustomValidity('')"/></textarea></div>
            <br>



            <input type="submit" value="Comment"        id="id_comment"  >
            <input type="hidden" value="send_Comment"  name="send_comment">
	    <br>
            {% csrf_token %}
        </form>

</div>



        <form method="POST" action="/">
            <input type="submit" value="Back" id="back" >
            <input type="hidden" value="Back_send" name="back_send" >
	    <br>
            {% csrf_token %}
        </form>
         {% if user.is_authenticated %}
         <form method="POST" action="/movie/{{movie_.id}}/edit/">
            <input type="submit" value="edit" id="Edit" >
            <input type="hidden" value="send_edit" name="send_Edit" >
	    <br>
            {% csrf_token %}
        </form>
        {% endif%}
</div>
<!-- end Shell -->
    </body>
</html>